### ISSUE TITLE
Uikit LESS?

### ISSUE THREAD

**Issue by bronze** [akshaybabloo/spark-hugo-theme#6]
Hi there man, im using your theme as a starting point to better develop a Hugo site.
One question though, any reason you went with a processed uikit instead of the .sass or .less one?

**Comment by akshaybabloo** [comment]
The processed UIKit is fine as is and I didn't need many changes too. That's why I just created a custom sass file and changed the colour.

**Comment by akshaybabloo** [comment]
I guess I have answered this question. Closing it.
